name: Edit Azure DevOps work item
on:
  issues:
    types:
      [edited, labeled, closed]
jobs:
  editWI:
    runs-on: ubuntu-latest
    steps:
      - uses: occmundial/github-to-azure-connector@main
        env:
          ado_token: "${{ secrets.AZURE_PAT_GH_TO_AZURE_CONNECTOR }}"
          github_token: "${{ secrets.GH_PAT_GH_TO_AZURE_CONNECTOR }}"
          ado_organization: "{ORGANIZATION NAME}"
          ado_project: "{PROJECT NAME}"
          github_issue_state: "edited"